### ISSUE TITLE
offers_automatic_updater.py doesn't work

### ISSUE THREAD

**Issue by cchriso** [giacomoferretti/mcdapi-tools#8]
The offers_automatic_updater.py script doesn't work for me

i get the offers.json file, but it has an empty {} json string
also this link isn't up anymore https://gist.github.com/giacomoferretti/a24797299041692613c155cac79b8127

Can you please send me a new scraped and parsed offers.json file for my bot to work properly? thank you

**Comment by giacomoferretti** [comment]
No, sorry. I will not public any more parsed offers. Also, in this period all the offers, in Italy, are disabled, so the bot is useless for now.

I don't maintain this script, tell Knocks.

Also, can you give us more information about your problem?

Version of Python: ?
Steps to reproduce: ?

**Comment by Knocks83** [comment]
It isn’t an issue, there isn’t any offer at the moment (there are the SummerDays)
